### ISSUE TITLE
Loading the translation fails with  version 1.0.1

### ISSUE THREAD

**Issue by liquidnight2** [longbridgeapp/rust-i18n#12]
In my project, I use your package which displayed the translated texts until yesterday.
Maybe there is another configuration setting missing ?

For discovering the issue  I created a separate most simple project:
https://github.com/liquidnight2/test-cases/tree/main/translationtest 
```

# cat locales/en.yml
en:
  hello : Hello_World-English!
  
  
#  cargo run
   Compiling translationtest v0.1.0 (/mnt/stripe/workspace1/test-cases/translationtest)
    Finished dev [unoptimized + debuginfo] target(s) in 34.39s
     Running `target/debug/translationtest`
translated=en.hello
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"en.hello"`,
 right: `"Hello_World-English!"`', src/main.rs:8:5

  ```

**Comment by huacnlee** [comment]
Just remove `en` language code:

```
en:
```

https://github.com/longbridgeapp/rust-i18n/releases/tag/v1.0.1

**Comment by liquidnight2** [comment]
Ok thanks, this solved the issue.
