### ISSUE TITLE
[BUG] cannot find function `translate` in the crate root

### ISSUE THREAD

**Issue by Sedorikku1949** [longbridgeapp/rust-i18n#13]
Hello, i am trying to use this crate, but when i use the macro `t`, i have this error:
```rs
error[E0425]: cannot find function `translate` in the crate root
  --> src\libs\i18n.rs:13:9
   |
13 |   dbg!(&t!("hello"));
   |         ^^^^^^^^^^^ not found in the crate root
   |
   = note: this error originates in the macro `t` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this function
   |
1  | use crate::i18n::translate;
   |

error[E0425]: cannot find function `translate` in the crate root
  --> src\libs\i18n.rs:14:9
   |
14 |   dbg!(&t!("hello"));
   |         ^^^^^^^^^^^ not found in the crate root
   |
   = note: this error originates in the macro `t` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this function
   |
1  | use crate::i18n::translate;
   |

```
*even if the compiler tells me to import the function, it doesn't exist !*
My code:
```rs
use rust_i18n::{ i18n, t };
use crate::utils;


pub fn load(logs: bool){
  i18n!("locales");
  if logs {
    utils::success("i18n", "Language modules ready to use")
  }
}

pub fn test(){
  dbg!(&t!("hello"));
  dbg!(&t!("hello"));
}
```

**Comment by huacnlee** [comment]
`i18n!` need use in outside the function.

```
use rust_i18n::{ i18n, t };
use crate::utils;

i18n!("locales");

pub fn load(logs: bool){
  if logs {
    utils::success("i18n", "Language modules ready to use")
  }
}

pub fn test(){
  dbg!(&t!("hello"));
  dbg!(&t!("hello"));
}
```

**Comment by Sedorikku1949** [comment]
> `i18n!` need use in outside the function. This is use for compile time, not runtime

The same error occured also when i18n! Is in a function

**Comment by huacnlee** [comment]
Would you please take a screenshot of your project, or submit code to GitHub public repo for give me source code to check?

**Comment by Sedorikku1949** [comment]
Here is a part of the source code: https://github.com/Sedorikku1949/MioEngine

The part of the code you may be most interested in is at `/src/libs/i18n.rs` from line 1 to line 18 (in comments)

*some files are not in the repository because they may leak several security information for my project and some secret data/protocols/information.*
*oh and, yes, the i18n.rs file is a mess, I try different options, that's why the code is so broken and bad x)*

**Comment by huacnlee** [comment]
The repo your updated is can not work.

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/5518/206394584-cfff3248-eacf-47c2-9aa9-981a7e5902a6.png">

Looks like you not have `locales` directory, and there is no `.yml` file.

**Comment by Sedorikku1949** [comment]
> The repo your updated is can not work.
> 
> 
> 
> Looks like you not have `locales` directory, and there is no `.yml` file. Would you please try like this:
> 
> <img width="1068" alt="image" src="https://user-images.githubusercontent.com/5518/206394584-cfff3248-eacf-47c2-9aa9-981a7e5902a6.png">

I deleted the .yml files and the locales directory, but when I tried to use them, this error occurred.

**Comment by jodev7** [comment]
![image](https://user-images.githubusercontent.com/80722162/208771589-325bf9d3-ba23-4bb3-9786-2c98094b3b38.png)

Same error

**Comment by huacnlee** [comment]
@jodev7 @Sedorikku1949 

Hi, 

I have wrote a simple example for use rust-i18n, would you please checkout it and find what difference of your use? 

https://github.com/longbridgeapp/rust-i18n-example

**Comment by HythamSoliman** [comment]
Same problem with me, any findings?

**Comment by l-7-l** [comment]
same here, need import translate from package

```rust
use identity::translate;
use rust_i18n::t;

fn main() {
    println!("{}", t!("hello", locale = "zh-CN"));

    println!("{}", t!("messages.hello", name = "world"));
}
```
 default-locale doesn't work either。 I tried to set it in the workspace root directory and the package directory respectively, but it didn't work
```
[workspace.metadata.i18n]
default-locale    = "zh-CN"
available-locales = ["en", "zh-CN"]
load-path         = "locales"
```

**Comment by zhongdongy** [comment]
I think you need to put 

```rust
rust_i18n::i18n!("locales");
```

to both `main.rs` (executable root), and your library root (`lib.rs` for example). So that all your library code and executable can make use of `t!(..)` macro. But do remember to keep it outside of any functions definitions.

**Comment by huacnlee** [comment]
@l-7-l You must init by use `rust_i18n::i18n!("locales")`

**Comment by huacnlee** [comment]
I am going to close this issue.

If there have any new problems, please submit new issue again.
