### ISSUE TITLE
Does not see locale in a docker container.

### ISSUE THREAD

**Issue by deepfunction** [longbridgeapp/rust-i18n#23]
// main.rs
rust_i18n::i18n!("locales");

// message_service.rs
use rust_i18n::t;

t!("invalidRequest", locale = locale.as_str()) return en.invalidRequest

If run not in a docker container all works fine.

How to configure it for docker container? Of course i copy locales folder with .yml files to container.

**Comment by MJoaaquin** [comment]
@deepfunction maybe it is a problem similar that happened to me, you can see my case here https://github.com/longbridgeapp/rust-i18n/pull/18

**Comment by arzt-arsch** [comment]
If you have `COPY . .` in your `Dockerfile` change it to `COPY . /root/project_name` or some other empty directory. I am assuming that when looking for available locales this library scans entire project directory, scanning root will take a **very** long time.

**Comment by huacnlee** [comment]
This may have been fixed in recent version, please try new version. If there have new issue, please feedback again.

I am going to close this.
