### ISSUE TITLE
Any option to load translation files at runtime?

### ISSUE THREAD

**Issue by stevepryde** [longbridgeapp/rust-i18n#28]
I'm looking for a translations solution for a WASM web frontend project, written in Rust.

I like the t! macro and this is awesome for development and for producing the correct translations etc.
However I don't want all of the translations bundled into the WASM file. This would make it far too large.
What I want instead is to allow the user to select their language and then download translations for the selected language from S3 or similar.

Would that be possible using this crate?

**Comment by huacnlee** [comment]
Version 2.0.0 release to allows you to this by custom Backend.
