### ISSUE TITLE
Separate `cargo i18n` to separate crate

### ISSUE THREAD

**Issue by urkle** [longbridgeapp/rust-i18n#45]
Including the i18n cargo cli tool in the main crate causes the whole crate to depend on packages such as clap (v2) when the main crate does not need it for use in an application.

I would recommend splitting that binary to a separate crate (rust-i18n-cli,  rust-i18n-cargo, cargo-i18n?) so that the dependencies can be reduced.

**Comment by urkle** [comment]
@huacnlee are you open to receiving a PR to implement this?  And how would you want the separate crate named?

**Comment by huacnlee** [comment]
Yes please, you can named it `rust-i18n-cli`
