### ISSUE TITLE
Incompatibility between "support" v2.1.0 and "macro" v2.0.0 silently breaks v2 builds.

### ISSUE THREAD

**Issue by Bruno02468** [longbridgeapp/rust-i18n#55]
A crate of mine now fails to build, and it took me a while to figure out why.

My project depends on `rust-i18n` with version selector `2`. That pulls the `support` sub-crate version `2.1.0` and the `macro` sub-crate version `2.0.0`, since these are the latest versions in the registry.

See, `SimpleBackend::new` [takes no arguments](https://docs.rs/rust-i18n-support/2.1.0/src/rust_i18n_support/backend.rs.html#54) in `support` version `2.1.0`, but the `i18n` macro in `macro` version `2.0.0` [generates a call to it that passes two](https://docs.rs/rust-i18n-macro/2.0.0/src/rust_i18n_macro/lib.rs.html#159).

Therefore, the `macro` crate, when on version `2.0.0`, shoud require that `support` also be version `2.0.0`, since in that version `SimpleBackend::new` [takes two arguments](https://docs.rs/rust-i18n-support/2.0.0/src/rust_i18n_support/backend.rs.html#67).

I've never published a package to the registry, so I don't know how one would go about amending past versions' dependencies, but publishing version `2.2.0` for the other sub-crates should work for now. I say that because the `macro` crate on `2.2.0` generates a [proper call](https://github.com/longbridgeapp/rust-i18n/blob/v2.2.0/crates/macro/src/lib.rs#L158) to `SimpleBackend::new` with no arguments.

**Comment by huacnlee** [comment]
Sorry, I have fixed this in `rust-i18n v2.2.1`, I just forgot to release the `rust-i18n-macro`.

**Comment by Bruno02468** [comment]
Woah, that was fast! My builds have come back to life. Thanks!
