### ISSUE TITLE
allow for value processor

### ISSUE THREAD

**Issue by GlenDC** [longbridgeapp/rust-i18n#6]
Not sure how or where I would implement it, but it would be nice if we could process our values prior to being stored in our in-memory hashmap. This could allow translators to use a minimal formatting language (e.g. markdown) so that I can store it as html snippets rather than still having to do this on the fly. I guess I could also do it manually of course, but that would mean I have the data twice.

**Comment by huacnlee** [comment]
This is not the I18n things, this crate just focus on I18n.
