### ISSUE TITLE
`t!` should return `&'static str` instead of `String`

### ISSUE THREAD

**Issue by eminfedar** [longbridgeapp/rust-i18n#61]
Returning probably have a program-wide lifetime hardly encoded string as `String` is not a good way I think.

Every time I called the `t!()` it creates and gives me ownership of the same string again and again.

I also can't use it where I need to temporarily create a `String` and take it's reference `.as_str()` to the function:
``` rust
set_toast_message(t!("Saving settings failed").as_str());
```
Error:
```rust
set_toast_message(t!("Saving settings failed").as_str());
    |                         -----------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^----------- temporary value is freed at the end of this statement
    |                         |                      |
    |                         |                      creates a temporary value which is freed while still in use
```

I think returning `&'static str` instead of `String` for program-wide available translations is good way to go.

**Comment by huacnlee** [comment]
Because there have some string template case, need to create new string.

For example:

```
hello: Hello %{name}
```

`t!("hello", name = "Jason")`

**Comment by eminfedar** [comment]
You are right 👍🏻 

For those who have the same problem, instead of directly using `t!()` in the function parenthesis, just define a let variable before:
```rust
let msg = t!("Saving settings failed);
set_toast_message(msg.as_str());
```
