### ISSUE TITLE
Recompile target if language files change

### ISSUE THREAD

**Issue by Arne91** [longbridgeapp/rust-i18n#62]
When the language files change, the changes are not applied and compiled.
I always have to change the .rs file where I use the macro 't!' to get the language changes in the binfile.

**Comment by limuy2022** [comment]
[another similai issue](https://github.com/longbridgeapp/rust-i18n/issues/46),you can use the build.rs like this issue to solve this.

**Comment by Arne91** [comment]
Ah perfect. That is exactly what I need. Thanks

**Comment by haheute** [comment]
This seems to work, too, to apply the latest changes in the locales file:

`cargo clean -p rust-i18n && cargo run`
