### ISSUE TITLE
t! macro doesn't work inside mod

### ISSUE THREAD

**Issue by franz65** [longbridgeapp/rust-i18n#78]
I have rust-i18n loaded in Cargo.toml as follows 
rust-i18n = "3.0.1"

when I call it inside main.rs it works fine:
```rs
use rust_i18n::*;
rust_i18n::i18n!("locales");

async fn main (){
    rust_i18n::set_locale("en");
   println!("locale {} test", t!("register", locale = "it-IT"))
}
```
I get the correct value printed.

But it doesn't work inside a module. I have a module called mytest, impoted in lib.rs.
Inside the module there is this code:

```rs
use rust_i18n::t;

pub fn test() {
    rust_i18n::set_locale("it-IT");
    println!("locale {} test", t!("register", locale = "it-IT"));
}
```

but when i try to compile I get this error:

```
error[E0425]: cannot find function `_rust_i18n_translate` in the crate root
 --> src/mytest/mytest.rs:9:33
  |
9 |     println!("locale {} test", t!("register", locale = "it-IT"));
  |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in the crate root
  |
  = note: this error originates in the macro `t` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I can't see what I'm doing wrong.
Thanks

**Comment by huacnlee** [comment]
Put `rust_i18n::i18n!` in lib.rs root:

```rs
use rust_i18n::{t, i18n};

i18n!();

fn test() {
   t!("...");
}
```

**Comment by franz65** [comment]
> Put `rust_i18n::i18n!` in lib.rs root:
> 
> ```rust
> use rust_i18n::{t, i18n};
> 
> i18n!();
> 
> fn test() {
>    t!("...");
> }
> ```

This works! Thanks
